# Publish GitHub workflow artifacts tutorial example
name: Publish GitHub Actions Artifacts Example

on:
  push:
    branches: [ main ]

jobs:
       
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:
    
      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: downloads
          
      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          
      - name: step 4 - 
        run: |

          sudo gem install asciidoctor-pdf --pre

          asciidoctor-pdf -a media=prepress -a pdf-theme=theme.yml -a pdf-fontsdir=./fonts _ebook.adoc -o _ebook.pdf

        

          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
